# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AOptimality <- function(currentDesign) {
    .Call('_rospd_AOptimality', PACKAGE = 'rospd', currentDesign)
}

calculateAOptimalityPseudo <- function(currentDesign) {
    .Call('_rospd_calculateAOptimalityPseudo', PACKAGE = 'rospd', currentDesign)
}

calculateDEfficiency <- function(currentDesign) {
    .Call('_rospd_calculateDEfficiency', PACKAGE = 'rospd', currentDesign)
}

#' @export
cDOptimality <- function(currentDesign) {
    .Call('_rospd_cDOptimality', PACKAGE = 'rospd', currentDesign)
}

DOptimalityBlocked <- function(currentDesign, blockedVar) {
    .Call('_rospd_DOptimalityBlocked', PACKAGE = 'rospd', currentDesign, blockedVar)
}

IOptimality <- function(currentDesign, momentsMatrix, blockedVar) {
    .Call('_rospd_IOptimality', PACKAGE = 'rospd', currentDesign, momentsMatrix, blockedVar)
}

